### ISSUE TITLE
Are there any alternative?

### ISSUE THREAD

**Issue by vivienneanthony** [TriAxis-Games/RuntimeMeshComponent#200]
I'm fixing up a plugin some to work with Unreal 4.25 using runtimemeshcomponent. I think it is using a old version of runtimemesh component. Since, I'm new to the component. Are some of this functions or changed deprecated? The code that I'm looking at is https://github.com/alteveer/Terrain/blob/master/Source/Terrain/Private/TerrainActor.cpp.

```
TerrainActor.cpp:31:26:   - error: no member named 'SetMeshSectionCollisionEnabled' in 'URuntimeMeshComponent'
        m_TerrainMeshComponent->SetMeshSectionCollisionEnabled(0, true);

TerrainActor.cpp:39:26:   - error: no member named 'ClearAllMeshSections' in 'URuntimeMeshComponent'
        m_TerrainMeshComponent->ClearAllMeshSections();

TerrainActor.cpp:78:28:   - error: no member named 'ClearMeshSection' in 'URuntimeMeshComponent'
                        m_TerrainMeshComponent->ClearMeshSection(it->Value);

TerrainActor.cpp:114:26:   - error: no member named 'ClearMeshSection' in 'URuntimeMeshComponent'
        m_TerrainMeshComponent->ClearMeshSection(section);

TerrainActor.cpp:115:52:   - error: no member named 'CreateMeshSection' in 'URuntimeMesh'
        m_TerrainMeshComponent->GetOrCreateRuntimeMesh()->CreateMeshSection(

TerrainActor.cpp:121:52:   - error: no member named 'SetSectionMaterial' in 'URuntimeMesh'
        m_TerrainMeshComponent->GetOrCreateRuntimeMesh()->SetSectionMaterial(section, DefaultMaterial);
```

**Comment by Moddingear** [comment]
These are rmcv3 functions, if you want to use the rmc the same way as in v3, there's the RuntimeMeshComponentStatic that's got the same functions exposed (names have slightly changed)
